version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.14-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my_network

  api-gateway:
    build:
      context: ./Backend/API-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - NODE_ENV=development
    depends_on:
      - auth-service
      - comment-service
      - post-service
      - post_details-service
      - rabbitmq
    networks:
      - my_network

  auth-service:
    build:
      context: ./Backend/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb+srv://amrithas172:jRc3s5RJmvjqXEmC@user.mnmdarm.mongodb.net/User?retryWrites=true&w=majority&appName=User
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - my_network

  comment-service:
    build:
      context: ./Backend/comment-service
      dockerfile: Dockerfile
    container_name: comment-service
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb+srv://amrithas172:jRc3s5RJmvjqXEmC@user.mnmdarm.mongodb.net/User?retryWrites=true&w=majority&appName=User
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
      - post_details-service
    networks:
      - my_network

  post-service:
    build:
      context: ./Backend/post-service
      dockerfile: Dockerfile
    container_name: post-service
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb+srv://amrithas172:jRc3s5RJmvjqXEmC@user.mnmdarm.mongodb.net/User?retryWrites=true&w=majority&appName=User
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
      - post_details-service

    networks:
      - my_network

  post_details-service:
    build:
      context: ./Backend/postDetails-service
      dockerfile: Dockerfile
    container_name: post_details-service
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb+srv://amrithas172:jRc3s5RJmvjqXEmC@user.mnmdarm.mongodb.net/User?retryWrites=true&w=majority&appName=User
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
