apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: post.com
      http:
        paths:
          - path: /api/user/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3001
          - path: /api/comment/?(.*)
            pathType: Prefix
            backend:
              service:
                name: comment-service
                port:
                  number: 3002
          - path: /api/post/?(.*)
            pathType: Prefix
            backend:
              service:
                name: post-service
                port:
                  number: 3003
          - path: /api/getPost/?(.*)
            pathType: Prefix
            backend:
              service:
                name: postDetails-service
                port:
                  number: 3004
